### ISSUE TITLE
Using swifter for text processing

### ISSUE THREAD

**Issue by hadyan-tvlk** [jmcarpenter2/swifter#13]
Hi guys,

I found difficulty how to effectively using swifter to do text processing. Since it cannot be vectorized, i hope we can leverage dask for parallelization.

For example, i have pandas dataframe with column name "text". then i have function that process text (name "clean_text") to do some simple text cleaning. my code is like this:

```
def clean_text(text):
    text = text.strip()
    text = text.replace(' ', '_')
    return text


df_data['text'] = df_data['text'].swifter.apply(clean_text)
```

but it throws error with following message:
```
TypeError: expected string or bytes-like object
```

Since the "text" variable type inside clean_text function is Pd.Series instead of String. 

why swift detect pd.series instead of string? Thanks

Stack I'm using:
- Pandas 0.23.4
- Dask 0.18.2
- Swifter 0.224

**Comment by jmcarpenter2** [comment]
Hi Mochammad,

Thank you for raising this issue. Could you please reply with the error you receive when you attempt to run the above code? Also your version of pandas, swifter, and dask would be invaluable.

I tried to create a toy example to replicate your error and am not experiencing any error when I run it. I believe you displaying the error, along with your version of pandas, swifter, and dask would be incredibly helpful to debugging this issue for you.

Thanks!

**Comment by ikkyle** [comment]
I'm getting this same error with string processing. 

``` python
def img_reader(file):
    path, name = os.path.split(file)
    newpath = os.path.join(path, '../png_redux', name)
    img = imread(newpath)
    return img

img_mat = meta_data['filename'].swifter.apply(img_reader)
```

Returns error

```
TypeError: expected str, bytes or os.PathLike object, not Series
```

Package versions:
```
pandas=0.23.4
dask==0.18.2
swifter==0.224
```

**Comment by jmcarpenter2** [comment]
Hi Roz,

Thanks for providing all those details! I understand the issue now: my vectorize call is in a try-catch but it doesn't currently catch TypeError exceptions. I have included this and released the new version 0.225.

Please give PyPi (pip) anywhere from 5-30min to integrate the new version and then try `pip install -U swifter` to upgrade.

Thank you both of raising this issue and contributing to the improvement of the package.

**Comment by hadyan-tvlk** [comment]
Hi @jmcarpenter2, thanks for the fixing. However, i'm still unable to solve this problem (after update it to 0.225), coming with the new error:

```
AttributeError: 'Series' object has no attribute 'swifter'
```

any idea? there is no change from the code for this error
