### ISSUE TITLE
Current Build 0.251 doesn't expose swiftapply

### ISSUE THREAD

**Issue by parnell** [jmcarpenter2/swifter#20]
Importing swiftapply doesn't currently work in the 0.251 build of swifter.

Minimal test case
test.py
```
from swifter import swiftapply
```

```
Traceback (most recent call last):
  File ".test.py", line 21, in <module>
    from swifter import swiftapply
ImportError: cannot import name 'swiftapply'
```

```
Requirement already up-to-date: swifter in /usr/local/lib/python3.6/site-packages (0.251)
Requirement already satisfied, skipping upgrade: pandas>=0.23.0 in /usr/local/lib/python3.6/site-packages (from swifter) (0.23.4)
Requirement already satisfied, skipping upgrade: tqdm in /usr/local/lib/python3.6/site-packages (from swifter) (4.26.0)
Requirement already satisfied, skipping upgrade: dask[complete]>=0.19.0 in /usr/local/lib/python3.6/site-packages (from swifter) (0.19.3)
Requirement already satisfied, skipping upgrade: psutil in /usr/local/lib/python3.6/site-packages (from swifter) (5.4.3)
Requirement already satisfied, skipping upgrade: pytz>=2011k in /usr/local/lib/python3.6/site-packages (from pandas>=0.23.0->swifter) (2018.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in /usr/local/lib/python3.6/site-packages (from pandas>=0.23.0->swifter) (2.6.1)
Requirement already satisfied, skipping upgrade: numpy>=1.9.0 in /usr/local/lib/python3.6/site-packages (from pandas>=0.23.0->swifter) (1.14.4)
Requirement already satisfied, skipping upgrade: toolz>=0.7.3; extra == "complete" in /usr/local/lib/python3.6/site-packages (from dask[complete]>=0.19.0->swifter) (0.9.0)
Requirement already satisfied, skipping upgrade: cloudpickle>=0.2.1; extra == "complete" in /usr/local/lib/python3.6/site-packages (from dask[complete]>=0.19.0->swifter) (0.6.0)
Requirement already satisfied, skipping upgrade: distributed>=1.22; extra == "complete" in /usr/local/lib/python3.6/site-packages (from dask[complete]>=0.19.0->swifter) (1.23.3)
Requirement already satisfied, skipping upgrade: partd>=0.3.8; extra == "complete" in /usr/local/lib/python3.6/site-packages (from dask[complete]>=0.19.0->swifter) (0.3.8)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas>=0.23.0->swifter) (1.11.0)
Requirement already satisfied, skipping upgrade: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.6/site-packages (from distributed>=1.22; extra == "complete"->dask[complete]>=0.19.0->swifter) (2.0.5)
Requirement already satisfied, skipping upgrade: tblib in /usr/local/lib/python3.6/site-packages (from distributed>=1.22; extra == "complete"->dask[complete]>=0.19.0->swifter) (1.3.2)
Requirement already satisfied, skipping upgrade: click>=6.6 in /usr/local/lib/python3.6/site-packages (from distributed>=1.22; extra == "complete"->dask[complete]>=0.19.0->swifter) (7.0)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python3.6/site-packages (from distributed>=1.22; extra == "complete"->dask[complete]>=0.19.0->swifter) (3.12)
Requirement already satisfied, skipping upgrade: zict>=0.1.3 in /usr/local/lib/python3.6/site-packages (from distributed>=1.22; extra == "complete"->dask[complete]>=0.19.0->swifter) (0.1.3)
Requirement already satisfied, skipping upgrade: msgpack in /usr/local/lib/python3.6/site-packages (from distributed>=1.22; extra == "complete"->dask[complete]>=0.19.0->swifter) (0.5.6)
Requirement already satisfied, skipping upgrade: tornado>=4.5.1 in /usr/local/lib/python3.6/site-packages (from distributed>=1.22; extra == "complete"->dask[complete]>=0.19.0->swifter) (5.0.2)
Requirement already satisfied, skipping upgrade: locket in /usr/local/lib/python3.6/site-packages (from partd>=0.3.8; extra == "complete"->dask[complete]>=0.19.0->swifter) (0.2.0)
Requirement already satisfied, skipping upgrade: heapdict in /usr/local/lib/python3.6/site-packages (from zict>=0.1.3->distributed>=1.22; extra == "complete"->dask[complete]>=0.19.0->swifter) (1.0.0)
```

**Comment by jmcarpenter2** [comment]
Hi @parnell,

In version 0.200 the expression for using swifter became more idiomatic.

Let's say you have some pandas dataframe

import pandas as pd
`df = pd.DataFrame(data=..., columns=...)`

Then using swifter is as follows
`import swifter`
`df.swifter.apply(func)`

This update is documented in the [README](https://github.com/jmcarpenter2/swifter/blob/master/README.md) and the [docs](https://github.com/jmcarpenter2/swifter/tree/master/docs)

I hope that helps!

**Comment by parnell** [comment]
Thanks @jmcarpenter2 . I was following a 3rd party tutorial and should have checked for an updated api.

**Comment by jmcarpenter2** [comment]
@parnell very interesting. Can I ask where the 3rd party tutorial was linking from? I suppose I should update my medium blog post where I introduced this function originally.
